### PR TITLE
Refactor to support asynchronous calls. Switching to aiohttp instead of requests

### PR DESCRIPTION
**Pull request by becutandavid**
Made a refactor to support asynchronous api calls. Haven't tested all the endpoints, only the one I need (episodesByFeedId).

### CODE REVIEW

**Comment by SarvagyaVaish** [comment]
Oops.. i missed this PR and just found the email deep in my inbox. 
Can you fix the conflicts please and I'll happily merge this in 🙏 Thanks so much for your contribution!

**Comment by SarvagyaVaish** [comment]
@ becutandavid this could be a valuable change. Will you have a chance to fix the conflicts?

**Comment by becutandavid** [comment]
Ah, I forgot about this PR. I'll fix the conflicts by the end of the week.

**Comment by becutandavid** [comment]
Tests passing. This is a breaking change, maybe play with it a little before deciding to merge.

I needed async support back when I made the pull request, and when I went over it againt now I have mixed feelings about forcing everyone to make async requests :)

**Comment by dbellotti** [comment]
@becutandavid

This looks great, although I am also concerned with the folks using the library who aren't ready to handle the change. Perhaps you can consider a design that would elegantly allow non async users to run the async code. 
```
import asyncio

def run_async(func):
    """Helper function to run coroutine in a new event loop."""
    return asyncio.new_event_loop().run_until_complete(func)

async def async_function():
    # Your async code here
    pass

# Users can call your async function like this:
run_async(async_function())
```
I think something like this could be implemented through a configuration option during `podcastindex.init()` or something.

@SarvagyaVaish this will break peoples code if they update without reading the diff.

**Comment by SarvagyaVaish** [comment]
Thanks, Davids! @becutandavid @dbellotti 

David Galevski, I really appreciate the work you put into this refactor! As David Bellotti mentioned, and you identified as well, I don't think this PR is ready as is to merge because of the backwards incompatibility. I think a wrapper approach is better. 

Closing for now :)

**Pull request closed without merging**
